# .github/workflows/ci.yml

name: Gemini CLI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run formatter check
        run: |
          npm run format
          git diff --exit-code

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run type check
        run: npm run typecheck

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.node-version }}
          path: |
            packages/*/dist
            package-lock.json # Only upload dist and lockfile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    permissions:
      contents: read
      checks: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [20.x] # Should match the build job's matrix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ matrix.node-version }}
          path: . # Download to the root, this will include package-lock.json and packages/*/dist

      # Restore/create package structure for dist folders if necessary.
      # The download-artifact action with path: . should place them correctly if the
      # upload paths were relative to the workspace root.
      # Example: if uploaded `packages/cli/dist`, it will be at `./packages/cli/dist`.

      - name: Install dependencies for testing
        run: npm ci # Install fresh dependencies using the downloaded package-lock.json

      - name: Run tests and generate reports
        run: NO_COLOR=true npm run test:ci

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (Node ${{ matrix.node-version }})
          path: packages/*/junit.xml
          reporter: java-junit
          fail-on-error: 'false'

      - name: Prepare Coverage Comment
        id: prep_coverage_comment
        shell: bash
        run: |
          cli_json_file="${{ github.workspace }}/packages/cli/coverage/coverage-summary.json"
          server_json_file="${{ github.workspace }}/packages/server/coverage/coverage-summary.json"
          cli_full_text_summary_file="${{ github.workspace }}/packages/cli/coverage/full-text-summary.txt"
          server_full_text_summary_file="${{ github.workspace }}/packages/server/coverage/full-text-summary.txt"
          comment_file="coverage-comment.md"

          # Extract percentages using jq for the main table
          if [ -f "$cli_json_file" ]; then
            cli_lines_pct=$(jq -r '.total.lines.pct' "$cli_json_file")
            cli_statements_pct=$(jq -r '.total.statements.pct' "$cli_json_file")
            cli_functions_pct=$(jq -r '.total.functions.pct' "$cli_json_file")
            cli_branches_pct=$(jq -r '.total.branches.pct' "$cli_json_file")
          else
            cli_lines_pct="N/A"; cli_statements_pct="N/A"; cli_functions_pct="N/A"; cli_branches_pct="N/A"
            echo "CLI coverage-summary.json not found at: $cli_json_file" >&2 # Error to stderr
          fi

          if [ -f "$server_json_file" ]; then
            server_lines_pct=$(jq -r '.total.lines.pct' "$server_json_file")
            server_statements_pct=$(jq -r '.total.statements.pct' "$server_json_file")
            server_functions_pct=$(jq -r '.total.functions.pct' "$server_json_file")
            server_branches_pct=$(jq -r '.total.branches.pct' "$server_json_file")
          else
            server_lines_pct="N/A"; server_statements_pct="N/A"; server_functions_pct="N/A"; server_branches_pct="N/A"
            echo "Server coverage-summary.json not found at: $server_json_file" >&2 # Error to stderr
          fi

          echo "## Code Coverage Summary" > "$comment_file"
          echo "" >> "$comment_file"
          echo "| Package | Lines | Statements | Functions | Branches |" >> "$comment_file"
          echo "|---|---|---|---|---|" >> "$comment_file"
          echo "| CLI | ${cli_lines_pct}% | ${cli_statements_pct}% | ${cli_functions_pct}% | ${cli_branches_pct}% |" >> "$comment_file"
          echo "| Server | ${server_lines_pct}% | ${server_statements_pct}% | ${server_functions_pct}% | ${server_branches_pct}% |" >> "$comment_file"
          echo "" >> "$comment_file"

          # CLI Package - Collapsible Section (with full text summary from file)
          echo "<details>" >> "$comment_file"
          echo "<summary>CLI Package - Full Text Report</summary>" >> "$comment_file"
          echo "" >> "$comment_file"
          echo '```text' >> "$comment_file"
          if [ -f "$cli_full_text_summary_file" ]; then
            cat "$cli_full_text_summary_file" >> "$comment_file"
          else
            echo "CLI full-text-summary.txt not found at: $cli_full_text_summary_file" >> "$comment_file"
          fi
          echo '```' >> "$comment_file"
          echo "</details>" >> "$comment_file"
          echo "" >> "$comment_file"

          # Server Package - Collapsible Section (with full text summary from file)
          echo "<details>" >> "$comment_file"
          echo "<summary>Server Package - Full Text Report</summary>" >> "$comment_file"
          echo "" >> "$comment_file"
          echo '```text' >> "$comment_file"
          if [ -f "$server_full_text_summary_file" ]; then
            cat "$server_full_text_summary_file" >> "$comment_file"
          else
            echo "Server full-text-summary.txt not found at: $server_full_text_summary_file" >> "$comment_file"
          fi
          echo '```' >> "$comment_file"
          echo "</details>" >> "$comment_file"
          echo "" >> "$comment_file"

          echo "_For detailed HTML reports, please see the 'coverage-reports-${{ matrix.node-version }}' artifact from this CI run._" >> "$comment_file"

          echo "comment_body<<EOF" >> "$GITHUB_OUTPUT"
          cat "$comment_file" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Post Coverage Comment
        uses: thollander/actions-comment-pull-request@v3
        if: always()
        with:
          message: ${{ steps.prep_coverage_comment.outputs.comment_body }}
          comment-tag: code-coverage-summary
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-${{ matrix.node-version }}
          path: packages/*/coverage
